### ISSUE TITLE
嗨，help

### ISSUE THREAD

**Issue by slince** [neven7/WeTest#2]
你好
![image](https://cloud.githubusercontent.com/assets/3785826/16911465/381d66f8-4d11-11e6-88e6-b6a139134afd.png)
我在测试的时候遇到了这个问题，请问下有没有`build_mail_status.xml`案例文件；我想先跑通你给的那个微博的测试案例
@neven7 
谢谢！
Tao

**Comment by neven7** [comment]
这周我抽空把文件修改下，再提交

**Comment by slince** [comment]
@neven7  我还挺着急的 如果你有这个文件的话 麻烦先发到给我下 taosikai@yeah.net 麻烦了

**Comment by neven7** [comment]
build.xml 已经添加到ant-build-file文件夹中
