### ISSUE TITLE
又遇到了新的问题

### ISSUE THREAD

**Issue by slince** [neven7/WeTest#3]
错误信息如下图：
![image](https://cloud.githubusercontent.com/assets/3785826/16937926/ae5376f2-4da5-11e6-845f-dab2c84acf99.png)
![image](https://cloud.githubusercontent.com/assets/3785826/16937938/c906ed1c-4da5-11e6-8a12-97feedf6773b.png)
java版本：
![image](https://cloud.githubusercontent.com/assets/3785826/16937945/d5396376-4da5-11e6-90ea-6e15c9f72020.png)

**Comment by neven7** [comment]
缺失依赖的jar包，在build.xml（范例文件中有标识）有个属性是设置class path的，这个路径下要放工程依赖的jar包；可以通过mvn dependency:copy-dependencies -DoutputDirectory=路径， 获取到maven工程依赖的jar包； UserPool是获取测试账号的，你可以不用，直接删除该文件。
